import { geoAlbersUsa, geoPath } from 'd3-geo';
import * as topojson from 'topojson-client';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const topoPath = path.resolve(__dirname, '../node_modules/us-atlas/states-albers-10m.json');
const topo = JSON.parse(readFileSync(topoPath, 'utf-8'));

// states-albers-10m is pre-projected onto a 975x610 canvas using Albers-USA
// with scale=1300, translate=[487.5, 305]. No projection needed for the paths.
const states = topojson.feature(topo, topo.objects.states);
const nation = topojson.merge(topo, topo.objects.states.geometries);

const toPath = geoPath();

// Round path numbers to keep bundle small.
const shrink = (d) =>
  d.replace(/-?\d+\.\d+/g, (m) => Number(m).toFixed(1));

let out = `// AUTO-GENERATED by scripts/build-us-map.mjs — do not edit.\n\n`;
out += `export const US_NATION_PATH = ${JSON.stringify(shrink(toPath(nation)))};\n\n`;
out += `export const US_STATE_PATHS: { id: string; name: string; d: string }[] = [\n`;
for (const f of states.features) {
  out += `  { id: ${JSON.stringify(String(f.id))}, name: ${JSON.stringify(f.properties.name)}, d: ${JSON.stringify(shrink(toPath(f)))} },\n`;
}
out += `];\n\n`;

// Waypoint cities as real geographic coordinates (lat, lon).
const cities = [
  { id: 'home',           name: 'Home',            region: 'Ohio',          lat: 39.4356, lon: -84.2033 },
  { id: 'lake-cumberland',name: 'Lake Cumberland', region: 'Kentucky',      lat: 36.9784, lon: -85.0619 },
  { id: 'mammoth-cave',   name: 'Mammoth Cave',    region: 'Kentucky',      lat: 37.1867, lon: -86.1000 },
  { id: 'new-river',      name: 'New River Gorge', region: 'West Virginia', lat: 38.0538, lon: -81.1042 },
  { id: 'nashville',      name: 'Nashville',       region: 'Tennessee',     lat: 36.1627, lon: -86.7816 },
  { id: 'hot-springs',    name: 'Hot Springs',     region: 'Arkansas',      lat: 34.5037, lon: -93.0552 },
  { id: 'st-louis',       name: 'St. Louis',       region: 'Missouri',      lat: 38.6270, lon: -90.1994 },
  { id: 'indiana-dunes',  name: 'Indiana Dunes',   region: 'Indiana',       lat: 41.6533, lon: -87.0524 },
  { id: 'home-return',    name: 'Back Home',       region: 'Ohio',          lat: 39.4356, lon: -84.2033 },
];

const proj = geoAlbersUsa().scale(1300).translate([487.5, 305]);

out += `export type ProjectedCity = { id: string; name: string; region: string; x: number; y: number };\n\n`;
out += `export const CITY_POINTS: ProjectedCity[] = [\n`;
for (const c of cities) {
  const p = proj([c.lon, c.lat]);
  if (!p) throw new Error(`Projection failed for ${c.name}`);
  out += `  { id: ${JSON.stringify(c.id)}, name: ${JSON.stringify(c.name)}, region: ${JSON.stringify(c.region)}, x: ${p[0].toFixed(2)}, y: ${p[1].toFixed(2)} },\n`;
}
out += `];\n`;

mkdirSync(path.resolve(__dirname, '../src/lib'), { recursive: true });
writeFileSync(path.resolve(__dirname, '../src/lib/us-map-generated.ts'), out);
console.log('wrote src/lib/us-map-generated.ts');
